// import Emprestimo from "/img/blog/emprestimo-saque-aniversario.png";
// import CarteiraDigital from "/img/blog/a-percepcao-dos-brasileiros-sobre-carteiras-digitais.png";
// import CartaoPorAproximacao from "/img/blog/cartao-por-aproximacao.png";

export const BLOGS = [
  {
    thumbnail: "./img/carros/carro-card-1.jpeg",
    title: "Carro de Luxo",
    // date: "26/06/2023",
    // slug: "importancia-da-analise-de-cpf-e-cnpj",
    category: "Veículo",
  },
  {
    thumbnail: "./img/carros/carro-card-2.jpeg",
    title: "Carro de Luxo",
    // date: "26/06/2023",
    // slug: "importancia-da-analise-de-cpf-e-cnpj",
    category: "Veículo",
  },
  {
    thumbnail: "./img/carros/carro-card-3.jpeg",
    title: "Carro de Luxo",
    // date: "26/06/2023",
    // slug: "importancia-da-analise-de-cpf-e-cnpj",
    category: "Veículo",
  },
  {
    thumbnail: "./img/carros/carro-card-4.jpeg",
    title: "Carro de Luxo",
    // date: "26/06/2023",
    // slug: "importancia-da-analise-de-cpf-e-cnpj",
    category: "Veículo",
  },
  {
    thumbnail: "./img/carros/carro-card-5.jpeg",
    title: "Carro de Luxo",
    // date: "26/06/2023",
    // slug: "importancia-da-analise-de-cpf-e-cnpj",
    category: "Veículo",
  },
  // {
  //   thumbnail: "./img/carros/carro-card-6.jpeg",
  //   title: "Carro de Luxo",
  //   // date: "26/06/2023",
  //   // slug: "importancia-da-analise-de-cpf-e-cnpj",
  //   category: "Veículo",
  // },
  // {
  //   thumbnail: "./img/carros/carro-card-7.jpeg",
  //   title: "Carro de Luxo",
  //   // date: "26/06/2023",
  //   // slug: "importancia-da-analise-de-cpf-e-cnpj",
  //   category: "Veículo",
  // },
  // {
  //   thumbnail: "./img/carros/carro-card-8.jpeg",
  //   title: "Carro de Luxo",
  //   // date: "26/06/2023",
  //   // slug: "importancia-da-analise-de-cpf-e-cnpj",
  //   category: "Veículo",
  // },
  // {
  //   thumbnail: "./img/carros/carro-card-9.jpeg",
  //   title: "Carro de Luxo",
  //   // date: "26/06/2023",
  //   // slug: "importancia-da-analise-de-cpf-e-cnpj",
  //   category: "Veículo",
  // },
  
  // {
  //   thumbnail: "/img/blog/como-descobrir-se-um-carro-ja-sofreu-acidentes-graves.jpg",
  //   title: "Como descobrir se um carro já sofreu acidentes graves?",
  //   date: "26/06/2023",
  //   slug: "como-descobrir-se-um-carro-ja-sofreu-acidentes-graves",
  //   category: "Veicular",
  // },
  // {
  //   thumbnail: "/img/blog/como-as-consultas-de-veiculos-podem-ajudar-na-compra-segura-de-um-carro-usado.jpg",
  //   title: "Como as consultas de veículos podem ajudar na compra segura de um carro usado?",
  //   date: "31/05/2023",
  //   slug: "como-as-consultas-de-veiculos-podem-ajudar-na-compra-segura-de-um-carro-usado",
  //   category: "Veicular",
  // },
  // {
  //   thumbnail: "/img/blog/como-verificar-a-procedência-de-um-veiculo.png",
  //   title: "Consultas veiculares: como verificar a procedência de um veículo antes de comprá-lo?",
  //   date: "16/05/2023",
  //   slug: "como-verificar-a-procedencia-de-um-veiculo-antes-de-compra-lo",
  //   category: "Veicular",
  // },
  // {
  //   thumbnail: "/img/blog/importancia-de-analise-de-fraudes.png",
  //   title: "Entenda a importância da análise de fraudes na prevenção de golpes virtuais",
  //   date: "05/05/2023",
  //   slug: "entenda-a-importancia-da-analise-de-fraudes-na-prevencao-de-golpes-virtuais",
  //   category: "Segurança",
  // },
  // {
  //   thumbnail: "/img/blog/importancia-das-consultas-antes-de-comprar-carro-usado.png",
  //   title: "Entenda a importância das consultas veiculares antes de comprar um carro usado",
  //   date: "01/05/2023",
  //   slug: "entenda-a-importancia-das-consultas-veiculares-antes-de-comprar-um-carro-usado",
  //   category: "Veicular",
  // },
  // {
  //   thumbnail: "/img/blog/como-as-consultas-de-cpf-previnem-fraudes.png",
  //   title: "Como as consultas de CPF podem ajudar a prevenir fraudes financeiras?",
  //   date: "24/04/2023",
  //   slug: "como-as-consultas-de-cpf-podem-ajudar-a-prevenir-fraudes-financeiras",
  //   category: "Crédito",
  // },
  // {
  //   thumbnail: "/img/blog/o-impacto-das-consultas-de-cnpj.png",
  //   title: "O impacto das consultas de CNPJ na seleção de fornecedores confiáveis.",
  //   date: "19/04/2023",
  //   slug: "o-impacto-das-consultas-de-cnpj-na-selecao-de-fornecedores-confiaveis",
  //   category: "Crédito",
  // },
  // {
  //   thumbnail: "/img/blog/emprestimo-saque-aniversario.png",
  //   title: "Empréstimo Saque-Aniversário: será que vale a pena?",
  //   date: "25/10/2022",
  //   slug: "emprestimo-saque-aniversario-sera-que-vale-a-pena",
  //   category: "Tecnologia",
  // },
  // {
  //   thumbnail: "/img/blog/a-percepcao-dos-brasileiros-sobre-carteiras-digitais.png",
  //   title: "A percepção dos brasileiros sobre carteiras digitais",
  //   date: "25/10/2022",
  //   slug: "a-percepcao-dos-brasileiros-sobre-carteiras-digitais",
  //   category: "Tecnologia",
  // },
  // {
  //   thumbnail: "/img/blog/cartao-por-aproximacao.png",
  //   title: "Cartão por aproximação: a tecnologia que veio para ficar",
  //   date: "25/10/2022",
  //   slug: "cartao-por-aproximacao-a-tecnologia-que-veio-para-ficar",
  //   category: "Tecnologia",
  // },
  // {
  //   thumbnail: "/img/blog/certificado-digital.png",
  //   title: "Como obter um certificado digital",
  //   date: "10/02/2023",
  //   slug: "como-obter-um-certificado-digital",
  //   category: "Tecnologia",
  // },
  // {
  //   thumbnail: "/img/blog/aumentar-score.png",
  //   title: "Como faço para aumentar meu Score?",
  //   date: "10/02/2023",
  //   slug: "como-faco-para-aumentar-meu-score",
  //   category: "Tecnologia",
  // },
];